name: SakuraBosses
version: '${project.version}'
main: io.github.itstaylz.sakurabosses.SakuraBossesPlugin
api-version: 1.18
authors: [ itsTaylz ]
depend: [Hexlib, Essentials]
load: STARTUP
commands:

  bossmenu:
    permission: sakurabosses.menu
    permission-message: §cNo permission

  bossesreload:
    permission: sakurabosses.reload
    permission-message: §cNo permission

  spawnboss:
    permission: sakurabosses.spawnboss
    permission-message: §cNo permission